version: '2'

services:
  consul:
    container_name: consul
    hostname: consul
    image: consul
    ports:
        - "8300-8303/tcp:8300-8303/tcp"
        - "8402/tcp:8402/tcp"
        - "8301-8302/udp:8301-8302/udp"
        - "8600/udp:8600/udp"
        - "8500/tcp:8500/tcp"

  registrator:
    container_name: registrator
    hostname: registrator
    depends_on:
        - consul
    image: gliderlabs/registrator
    command: -internal -ip="172.17.0.1" consul://consul:8500
    links:
        - "consul:consul"
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"

  fabio:
    container_name: fabio
    hostname: fabio
    depends_on:
        - consul
    image: magiconair/fabio
    ports:
        - "9998:9998"
        - "9999:9999"
    links:
        - "consul:consul"
    volumes:
        - $PWD/fabio:/etc/fabio

  frontend:
    depends_on:
        - registrator
        - fabio
    build: frontend/
    expose:
        - "8000"
    links:
        - "registrator:registrator"
    environment:
        - SERVICE_NAME=frontend
        - SERVICE_TAGS=urlprefix-/ 
        - SERVICE_CHECK_HTTP=/
        - SERVICE_CHECK_INTERVAL=5s


